org: yanghaoyuying
# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: awesomeSite

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

# The `functions` block defines what code to deploy
functions:
  app:
    handler: handler.awesomeSite
    # The `events` block defines how to trigger the http events
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
